id: PEEBEDE5F
initial_creation_type: input
source_metadata:
  title: Ratna Lingpa Series
  language: es
  description: 'Texts by the famous treasure-revealer Ratna Lingpa (ratna gling pa,
    1403-1479):'
  volume:
    18b5a37e310f4e42af989e6451a50bc7:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Guru Padmasambhava
    36420ac3f2294b9c89f4c75083f2138d:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Guru Padmasambhava
    0025ba0513a3445893eee298064c6467:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Tārā
created_at: '2022-03-01T01:19:45.927556'
last_modified_at: '2022-03-01T01:19:45.927558'
